<?php

namespace Glhd\Linearavel\Requests\Inputs;

use Illuminate\Support\Collection;

/** @see https://studio.apollographql.com/public/Linear-API/variant/current/schema/reference/inputs/IssueCollectionFilter */
class IssueCollectionFilterInput
{
	public function __construct(
		public ?IssueIDComparatorInput $id = null,
		public ?DateComparatorInput $createdAt = null,
		public ?DateComparatorInput $updatedAt = null,
		public ?NumberComparatorInput $number = null,
		public ?StringComparatorInput $title = null,
		public ?NullableStringComparatorInput $description = null,
		public ?NullableNumberComparatorInput $priority = null,
		public ?EstimateComparatorInput $estimate = null,
		public ?NullableDateComparatorInput $startedAt = null,
		public ?NullableDateComparatorInput $triagedAt = null,
		public ?NullableDateComparatorInput $completedAt = null,
		public ?NullableDateComparatorInput $canceledAt = null,
		public ?NullableDateComparatorInput $slaBreachesAt = null,
		public ?NullableDateComparatorInput $archivedAt = null,
		public ?NullableDateComparatorInput $autoClosedAt = null,
		public ?NullableDateComparatorInput $autoArchivedAt = null,
		public ?NullableDateComparatorInput $addedToCycleAt = null,
		public ?CyclePeriodComparatorInput $addedToCyclePeriod = null,
		public ?NullableTimelessDateComparatorInput $dueDate = null,
		public ?NullableDateComparatorInput $accumulatedStateUpdatedAt = null,
		public ?NullableDateComparatorInput $snoozedUntilAt = null,
		public ?NullableUserFilterInput $assignee = null,
		public ?NullableUserFilterInput $delegate = null,
		public ?NullableTemplateFilterInput $lastAppliedTemplate = null,
		public ?NullableTemplateFilterInput $recurringIssueTemplate = null,
		public ?SourceMetadataComparatorInput $sourceMetadata = null,
		public ?NullableUserFilterInput $creator = null,
		public ?NullableIssueFilterInput $parent = null,
		public ?NullableUserFilterInput $snoozedBy = null,
		public ?IssueLabelCollectionFilterInput $labels = null,
		public ?UserCollectionFilterInput $subscribers = null,
		public ?RelationExistsComparatorInput $hasSharedUsers = null,
		public ?UserCollectionFilterInput $sharedWith = null,
		public ?TeamFilterInput $team = null,
		public ?NullableProjectMilestoneFilterInput $projectMilestone = null,
		public ?CommentCollectionFilterInput $comments = null,
		public ?ActivityCollectionFilterInput $activity = null,
		public ?IssueSuggestionCollectionFilterInput $suggestions = null,
		public ?NullableCycleFilterInput $cycle = null,
		public ?NullableProjectFilterInput $project = null,
		public ?WorkflowStateFilterInput $state = null,
		public ?IssueCollectionFilterInput $children = null,
		public ?AttachmentCollectionFilterInput $attachments = null,
		public ?ContentComparatorInput $searchableContent = null,
		public ?RelationExistsComparatorInput $hasRelatedRelations = null,
		public ?RelationExistsComparatorInput $hasDuplicateRelations = null,
		public ?RelationExistsComparatorInput $hasBlockedByRelations = null,
		public ?RelationExistsComparatorInput $hasBlockingRelations = null,
		public ?RelationExistsComparatorInput $hasSuggestedRelatedIssues = null,
		public ?RelationExistsComparatorInput $hasSuggestedSimilarIssues = null,
		public ?RelationExistsComparatorInput $hasSuggestedAssignees = null,
		public ?RelationExistsComparatorInput $hasSuggestedProjects = null,
		public ?RelationExistsComparatorInput $hasSuggestedLabels = null,
		public ?RelationExistsComparatorInput $hasSuggestedTeams = null,
		public ?RelationExistsComparatorInput $hasActiveAgentSessions = null,
		public ?RelationExistsComparatorInput $hasDismissedAgentSessions = null,
		public ?RelationExistsComparatorInput $hasErroredAgentSessions = null,
		public ?RelationExistsComparatorInput $hasMergedAgentPullRequests = null,
		public ?SlaStatusComparatorInput $slaStatus = null,
		public ?ReactionCollectionFilterInput $reactions = null,
		public ?CustomerNeedCollectionFilterInput $needs = null,
		public ?ReleaseCollectionFilterInput $releases = null,
		public ?NumberComparatorInput $customerCount = null,
		public ?NumberComparatorInput $customerImportantCount = null,
		public ?NullableDurationComparatorInput $leadTime = null,
		public ?NullableDurationComparatorInput $cycleTime = null,
		public ?NullableDurationComparatorInput $ageTime = null,
		public ?NullableDurationComparatorInput $triageTime = null,
		/** @var iterable<IssueCollectionFilterInput>|Collection<int, IssueCollectionFilterInput> */
		public ?iterable $and = null,
		/** @var iterable<IssueCollectionFilterInput>|Collection<int, IssueCollectionFilterInput> */
		public ?iterable $or = null,
		public ?IssueFilterInput $some = null,
		public ?IssueFilterInput $every = null,
		public ?NumberComparatorInput $length = null
	) {
	}
}
