<?php

namespace Glhd\Linearavel\Data;

use Carbon\CarbonImmutable;
use Glhd\Linearavel\Data\Casts\LinearDate;
use Glhd\Linearavel\Data\Contracts\Node;
use Glhd\Linearavel\Data\Enums\DraftUpdateHealthType;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Optional;

/** @see https://studio.apollographql.com/public/Linear-API/variant/current/schema/reference/objects/Draft */
class Draft extends Data implements Node
{
	public function __construct(
		public Optional|string $id,
		#[LinearDate]
		public Optional|CarbonImmutable $createdAt,
		#[LinearDate]
		public Optional|CarbonImmutable $updatedAt,
		public Optional|string $bodyData,
		public Optional|bool $isAutogenerated,
		public Optional|bool $wasLocalDraft,
		public Optional|User $user,
		#[LinearDate]
		public Optional|CarbonImmutable|null $archivedAt,
		public Optional|string|null $data,
		public Optional|DraftUpdateHealthType|null $updateHealth,
		public Optional|DraftGenerationMetadata|null $generationMetadata,
		public Optional|Issue|null $issue,
		public Optional|Project|null $project,
		public Optional|ProjectUpdate|null $projectUpdate,
		public Optional|Initiative|null $initiative,
		public Optional|InitiativeUpdate|null $initiativeUpdate,
		public Optional|Post|null $post,
		public Optional|Comment|null $parentComment,
		public Optional|CustomerNeed|null $customerNeed,
		public Optional|PullRequest|null $pullRequest,
		public Optional|string|null $anchor,
		public Optional|Team|null $team
	) {
	}
}
