name: Code Style

on: [ pull_request, push ]

jobs:
  code-style:
    runs-on: ubuntu-latest

    name: Run code style checks

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, iconv
          tools: composer:v2

      - name: Register the Composer cache directory
        id: composer-cache-files-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ${{ steps.composer-cache-files-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run
